services:
  zerobyte-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: zerobyte
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
      - APP_SECRET=94bad4678ce84a60b9789bd2114a6bf780aeb38df426f7352c941c66e25d5c2b
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - ./app:/app/app
      - ~/.config/rclone:/root/.config/rclone

  zerobyte-prod:
    # image: ghcr.io/nicotsx/zerobyte:v0.22.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - APP_VERSION=0.20.0
    container_name: zerobyte
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    environment:
      - APP_SECRET=94bad4678ce84a60b9789bd2114a6bf780aeb38df426f7352c941c66e25d5c2b
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - ~/.config/rclone:/root/.config/rclone

  zerobyte-e2e:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: zerobyte
    restart: unless-stopped
    environment:
      - DISABLE_RATE_LIMITING=true
      - APP_SECRET=94bad4678ce84a60b9789bd2114a6bf780aeb38df426f7352c941c66e25d5c2b
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./playwright/data:/var/lib/zerobyte/data
      - ./playwright/temp:/test-data
